### ISSUE TITLE
Custom color chart

### ISSUE THREAD

**Issue by Frolipon** [Badsender-com/LePatron.email#318]
# Description

As **account administrator**,
I would like **to be able to define custom colours,**
In order to **have a colour scheme consistent with my graphic charter from the editor.**

## Value
Fluidity in client management and template initialization. Autonomy, time saving

## Rules

- If no custom colour scheme is defined by the account administrator, then leave the default colour scheme (material)
- If a custom colour scheme is defined by the account administrator, then the users of the account see it directly from the style editor
- The color picker functionality (double arrows and choice of material, color scale, custom) is removed
- The color picker is still available to account users and administrators from the editor
- The custom colour picker is available to the administrator in *Settings > Information tab*.
- 21 custom colours maximum (7 per line in the color picker and 3 lines max)

## Acceptance criteria

- Since I am on the account information admin page, when I click on blank shades as not filled in, then the color picker appears and I can define a new custom colour
- Since I am on the account information administration page, when I save the changes, then the custom colour scheme is available on the editor for all users of the account
- As I am on the template edit page, when I click on a colour field, then the colour picker is displayed and I can use the custom colour scheme

## Mockup / Screenshot

admin custom colors manager

![118961737-f26c8b00-b964-11eb-8b37-c4afcfed0a16](https://user-images.githubusercontent.com/5319082/121905675-b392e080-cd2a-11eb-9183-f1d4a31550a7.png)

default color picker

![118961761-f8626c00-b964-11eb-98a6-ec06041038ba](https://user-images.githubusercontent.com/5319082/121905712-bc83b200-cd2a-11eb-9301-b2320483c07d.png)

color picker with custom colors

![118961773-fc8e8980-b964-11eb-9521-9346ca2bcbbd](https://user-images.githubusercontent.com/5319082/121905738-c2799300-cd2a-11eb-9c27-69a472d2739e.png)

**Comment by lexie-claudia** [comment]
# Test feedback (2021/10/15)

Tested on Safari.

I logged on, went into 'Reglages' and was able to add/ delete a colour from the colour scheme. I selected 'Enregistrer' but found the new colour I added wasn't saved when I went to 'Retourner aux emails' -> test mathilde -> I then clicked on Clarins banner on the page -> clicked on 'Style' and when I selected the colour picker next to 'color on mouse over' the colour scheme was not updated there.
