### ISSUE TITLE
Download emails from the backoffice

### ISSUE THREAD

**Issue by Frolipon** [Badsender-com/LePatron.email#324]
# Description

As a **user**,
I would like to **be able to download one or more emails directly from the list** available on the backoffice,
in order to save time and **not have to go through the editor**

## Value

productivity and batch processing

## Rules

- **batch**: when I am in the backoffice, in a workspace or a directory, I can select one or more emails and have a download action for this selection
- **shortcut**: Always at the level of the list of available emails, in the actions proposed for the email, I can download it without having to open it

## Mockup / Screenshot

**Batch**

![batch-action](https://user-images.githubusercontent.com/5319082/122065618-624e2400-cdf2-11eb-817c-940b5af5dc7e.png)

![batch-download](https://user-images.githubusercontent.com/5319082/122065643-6712d800-cdf2-11eb-85cc-75ced3de015f.png)

**Shortcut**

![shortcut-download](https://user-images.githubusercontent.com/5319082/122065694-6f6b1300-cdf2-11eb-838d-f47e98b9e681.png)

**Comment by medamineziraoui** [comment]
In the mails listing for Regular user and Group admin:
- We can download a single with local download ( images included inside the downloaded zip ) mail from list
- If the FTP is provided in the group by the super admin, we can download single mail with images pointing to FTP server.
- We can download multiple mails with local download
- If FTP also provided we can download multiple with images pointing to ftp.
- When downloading multiple mails we need to keep all mails, even if they have the same name ( a number will be added to the name of the mailin that case )
- When downloading mails the name will be `lepatron.zip`
