### ISSUE TITLE
Retrieve the email after saving it

### ISSUE THREAD

**Issue by the2ne** [Badsender-com/LePatron.email#407]
## Description

As a **user**
I want to be able to **find my email in the backoffice listing after saving it from the editor**
So that I **don't waste time browsing worspaces and folders** 

- Value: saving time and mental load

## Rules

- If I **open or create an email** **from a workspace and/or a folder**, after having modified it from the editor and then saved it, then I **come back to the corresponding workspace/folder listing**.

**Comment by medamineziraoui** [comment]
Refused: 
When we create a mail for the first time and open it, we get redirected to the mails listing.
