### ISSUE TITLE
List and groups of email addresses

### ISSUE THREAD

**Issue by the2ne** [Badsender-com/LePatron.email#408]
## Description

As **a group admin**,
I would like to **create lists of email addresses and group them** together
To be able to **send test mails directly to a group** of my choice

- Value: no double input, no support

**Comment by Malek-khannoussi** [comment]
## Note
When the user testing a email and trying to test (send the email), the group entry works perfectly, but the E-mail input doesn't have a placeholder (this only doesn't work when the user is using French)
## Screenshot
![image](https://user-images.githubusercontent.com/90857479/133780067-ba2941ed-b730-4c3a-abae-c2de3820557b.png)
## Navigator
Google chrome
## Tested in 
17-09

**Comment by Malek-khannoussi** [comment]
## Note
When the group admin testing a email and trying to test (send the email), he let you select the group and don't show any error but when press "ENVOYER UN MAIL DE TEST" the application show error message with this error in console
`Unable to preventDefault inside passive event listener invocation.   badsender-editor.min.js:1 `
## screenshot
![image](https://user-images.githubusercontent.com/90857479/133780697-a9317cc1-225d-4e7c-8082-1cd0336ef506.png)

**Comment by Malek-khannoussi** [comment]
## Note
the E-mail doesn't work when write many emails with ; at the end and show in helper.
"Emails are invalid,please enter valiid emails separated by ;
## Screenshot
![image](https://user-images.githubusercontent.com/90857479/133781854-72abbec2-27a0-4a2d-a380-69ef67738eef.png)
## Navigator
Google chrome
## Tested in
17-09

**Comment by medamineziraoui** [comment]
`error in console
Unable to preventDefault inside passive event listener invocation. badsender-editor.min.js:1` seems to be the reason of using `vue-select` with the `vue/dist/vue.common` 

We extracted this bug to another issue https://github.com/Badsender-com/LePatron.email/issues/476, this error doesn't block or trigger unwanted behavior in the editor. We recommand fixing it in other release so we don't block the current release

**Comment by medamineziraoui** [comment]
This feedback is not valid, because the helper did indicate to get the emails sepected by `;` ,  not adding `;` in the end
