### ISSUE TITLE
Link target attributes on exported emails

### ISSUE THREAD

**Issue by the2ne** [Badsender-com/LePatron.email#464]
### Observation

The builder applies a `taget="_new"` when exporting HTML whether or not there is a `target="_blank"` defined in the template.

### Need

1. If the template contains a link with a `target="_blank"` attribute then the builder must not replace it when exporting the HTML.
2. Otherwise, if there is no target specified, it can apply a `target="_new"` as is currently the case.

**Comment by Malek-khannoussi** [comment]
## Note
the builder applies a target="_new" to some links have target="_blank"
## example
in x template `clarins` the links in header `NOUVEAUT , SOINS, MAQUILLAGE,  OFFRES, UNIVERS CLARINS ` has had a `target="_blank"` and after downloading they convert to `target="_new" `
## screenshot
**to the right is the template**
 **to the left is the file after downloading**
![image](https://user-images.githubusercontent.com/90857479/133818250-98f258ae-0386-40b9-9452-c89b2c2b0458.png)
